"""Verify generated files and line endings against retained JVM producer trees."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import tarfile
import zipfile

from collect_controlled_sources import validate_file_inventory
from collect_jvm_build_inputs import match_source_files, source_tree_index
from package_controlled_payloads import digest


def render_template(name, module, template):
    if module["name"] in {"jackson-core", "jackson-databind"} and name.endswith("/PackageVersion.java"):
        substitutions = {"@package@": name.rsplit("/", 1)[0].replace("/", "."),
                         "@projectversion@": module["version"], "@projectgroupid@": module["group"],
                         "@projectartifactid@": module["name"]}
    elif module["name"] == "okhttp" and name == "okhttp3/OkHttp.kt":
        substitutions = {"$projectVersion": module["version"]}
    elif module["name"] == "kotlin-stdlib" and name == "commonMain/kotlin/util/KotlinVersion.kt":
        text = template.decode()
        pattern = r"fun get\(\): KotlinVersion = KotlinVersion\((\d+, \d+, \d+)\)"
        matches = list(re.finditer(pattern, text))
        if len(matches) != 1 or re.fullmatch(r"\d+\.\d+\.\d+", module["version"]) is None:
            raise ValueError("Unexpected Kotlin version source")
        substitutions = {matches[0].group(1): ", ".join(module["version"].split("."))}
        start, end = matches[0].span(1)
        return (text[:start] + next(iter(substitutions.values())) + text[end:]).encode(), substitutions
    elif module.get("group", "").startswith("org.jetbrains.compose.") and name == "redirectCommonMain/EmptyRedirectRoot.kt":
        generator = 'f.writeText("// Auto-generated by artifactRedirection redirect { } for \'$path\'.\\n")'
        if generator not in template.decode():
            raise ValueError("Compose redirect generator differs from reviewed implementation")
        group_path = module["group"].removeprefix("org.jetbrains.").replace(".", ":")
        path = ":" + group_path + ":" + module["name"].removesuffix("-android")
        return ("// Auto-generated by artifactRedirection redirect { } for '" + path + "'.\n").encode(), {"$path": path}
    else:
        raise ValueError("Unknown generated source; do not assume it is a version template")
    text = template.decode()
    for token, value in substitutions.items():
        if text.count(token) != 1:
            raise ValueError("Unexpected generating template token")
        text = text.replace(token, value)
    return text.encode(), substitutions


def verify(jvm, build_inputs, output):
    if output.exists():
        raise ValueError("Preserve previous review results")
    report = json.loads((build_inputs / "JVM-BUILD-INPUTS.json").read_text())
    validate_file_inventory(build_inputs, report)
    graph = json.loads((jvm / "JVM-SOURCE-INVENTORY.json").read_text())
    records, normalized = [], []
    artifact_count, exact_count = 0, 0
    for project in report["projects"]:
        index = source_tree_index(build_inputs / project["file"])
        with tarfile.open(build_inputs / project["file"]) as tree:
            members = [entry for entry in tree if entry.isfile()]
            for artifact in [project, *project.get("relatedArtifacts", [])]:
                module = artifact["module"]
                item = next(x for x in graph["artifacts"] if x["binary"].get("module") == module)
                source = next(x for x in item["downloads"] if x["file"].endswith("-sources.jar"))
                if digest(jvm / source["file"]) != source["sha256"]:
                    raise ValueError("Preserved Maven source JAR changed")
                matching = match_source_files(jvm / source["file"], build_inputs / project["file"], index)
                if matching != artifact["sourceMatches"]:
                    raise ValueError("Previously recorded upstream source matches changed")
                artifact_count += 1
                exact_count += matching["exactSourceMatches"]
                with zipfile.ZipFile(jvm / source["file"]) as jar:
                    for name in matching["unmatched"]:
                        published = jar.read(name)
                        if module["name"] == "annotations":
                            candidates = [m for m in members if Path(m.name).name == Path(name).name]
                            matches = [m for m in candidates if tree.extractfile(m).read().replace(b"\r\n", b"\n") ==
                                       published.replace(b"\r\n", b"\n")]
                            if len(matches) != 1:
                                raise ValueError("Annotation source differs beyond line endings")
                            normalized.append({"module": module, "sourceJarFile": name,
                                               "upstreamFile": matches[0].name,
                                               "transformation": "CRLF/LF only",
                                               "sha256": hashlib.sha256(published).hexdigest()})
                            continue
                        if name == "commonMain/kotlin/util/KotlinVersion.kt":
                            suffix = "libraries/stdlib/src/kotlin/util/KotlinVersion.kt"
                            generators = [m for m in members if m.name.endswith("/prepare/build.version/build.gradle.kts")]
                            if len(generators) != 1 or "val writeStdlibVersion" not in tree.extractfile(generators[0]).read().decode():
                                raise ValueError("Kotlin version generator missing")
                        elif name == "redirectCommonMain/EmptyRedirectRoot.kt":
                            suffix = "buildSrc/private/src/main/kotlin/org/jetbrains/androidx/build/ArtifactRedirection.kt"
                        else:
                            suffix = name + ".in" if name.endswith("/PackageVersion.java") else "java-templates/" + name
                        templates = [m for m in members if m.name.endswith("/" + suffix)]
                        if len(templates) != 1:
                            raise ValueError("Generating source template missing or ambiguous: " + name)
                        template = templates[0]
                        rendered, substitutions = render_template(name, module, tree.extractfile(template).read())
                        if rendered != published:
                            raise ValueError("Generated Maven source differs from producing template: " + name)
                        records.append({"module": module, "sourceJarFile": name,
                                        "templateFile": template.name, "substitutions": substitutions,
                                        "sha256": hashlib.sha256(rendered).hexdigest()})
        print(f"{project['module']['name']}: source differences verified", flush=True)
    result = {"projects": len(report["projects"]), "generatedSourceMatches": records,
              "artifacts": artifact_count, "lineEndingMatches": normalized, "exactSourceFiles": exact_count,
              "completeCorrespondingSourcesVerified": False,
              "scope": "Preserved producer trees and their related artifacts; not the entire JVM producer graph"}
    output.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps({"projects": result["projects"], "exactSourceFiles": result["exactSourceFiles"],
                      "generatedSourceFiles": len(records)}))
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("jvm", "build-inputs", "output"):
        parser.add_argument("--" + name, type=Path, required=True)
    args = parser.parse_args()
    verify(args.jvm, args.build_inputs, args.output)
